version: "3"
services:
  lighthouse:
    image: nickc/lighthouse:latest
    container_name: lighthouse
    stdin_open: true
    networks:
      default:
        ipv4_address: 172.22.144.2
  trackingservice:
    image: nickc/trackingservice:latest
    container_name: trackingservice
    stdin_open: true
    depends_on:
      - "lighthouse"
  crawlservice:
    image: nickc/crawlservice:latest
    container_name: crawlservice_1
    stdin_open: true
    depends_on: 
      - "trackingservice"
  web:
    image: nickc/webcrawlerweb:latest
    container_name: web
    depends_on:
      - "crawlservice"
    networks:
      default:
        ipv4_address: 172.22.144.3
networks:
  default:
    external:
      name: nat